version: '3'

services:
    
    dbos:
      image: mysql:5.7
      volumes:
        - db_storage:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_USER: mayank
        MYSQL_PASSWORD: redhat
        MYSQL_DATABASE: mydb
      restart: always
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure

    wordpress_os:
      image: wordpress:5.1.1-php7.3-apache
      volumes:
        - wp_storage:/var/www/html
      environment:
        WORDPRESS_DB_PASSWORD: redhat
        WORDPRESS_DB_NAME: mydb
        WORDPRESS_DB_HOST: dbos
        WORDPRESS_DB_USER: mayank
      restart: always
      depends_on:
        - dbos
      ports:
        - 8081:80
      deploy:
        replicas: 2
        restart_policy: 
          condition: on-failure

volumes:
    db_storage:
    wp_storage:
